name: Output Dockerfile

on: [push]
env:
  SERVER_IMAGE: request-bin-api
  DB_IMAGE: request-bin-db
  DOCKER_USER: chrisdurand


jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Output Dockerfile
        id: build-server-df
        uses: ChristopherDurand/build-node-postgres-react-action@v8
        with:
          build-type: "npmNodeReact"
          schema:
          seed-data:
      - name: Checkout PR Code
        run: actions/checkout@v1
      - name: Build Backend Image
        run: echo -e '${{steps.build-server-df.outputs.server-df}}' |\ #Pipe the dockerfile in
          docker build \ #
          -t chrisdurand:latest \ 
          -f- . #Get the dockerfile from std in, and use the current directory as the build context
