name: Publish Image to ECR
on: [push]

env:
  ECR_REPO: request-bin
  SERVER_PATH: server/
  BUILDER: gcr.io/buildpacks/builder:v1
jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Install Pack CLI
        id: install-pack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli && \
          sudo apt-get update && \
          sudo apt-get install pack-cli
      - name: build, tag, and push image using Google Builder
        id: build-server
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          pack build $ECR_REGISTRY/$ECR_REPO:$GITHUB_SHA \
          --builder $BUILDER \
          --path $SERVER_PATH \
          --cache-image $ECR_REGISTRY/$ECR_REPO:cache \
          --publish
      - name: write task definition for image
        id: task-gen
        uses: Mush-Framework/create-task-definition
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          server-arn: $ECR_REGISTRY/$ECR_REPO:$GITHUB_SHA
          migration: db/migration.sql
          db-name: request-bin
          app-name: request-bin
      - name: Log the task definition to the console.
        run: echo ${{ steps.task-gen.outputs.task-definition }}
