name: Publish Image
# Minimum Required Permissions for Pushing and Pulling Images
# {
#    "Version":"2012-10-17",
#    "Statement":[
#       {
#          "Sid":"AllowPush",
#          "Effect":"Allow",
#          "Action":[
#             "ecr:GetDownloadUrlForLayer",
#             "ecr:BatchGetImage",
#             "ecr:BatchCheckLayerAvailability",
#             "ecr:PutImage",
#             "ecr:InitiateLayerUpload",
#             "ecr:UploadLayerPart",
#             "ecr:CompleteLayerUpload"
#          ],
#          "Resource":"arn:aws:ecr:us-east-1:123456789012:repository/my-repo"
#       }
#    ]
# }
on: push

env:
  ECR_REPO: request-bin
jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Install Pack CLI
        id: install-pack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli && \
          sudo apt-get update && \
          sudo apt-get install pack-cli
      - name: build, tag, and push image using Google Builder
        id: build-server
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          pack build $ECR_REGISTRY/$ECR_REPO:$GITHUB_SHA \
          --builder gcr.io/buildpacks/builder:v1 \
          --path server/ \
          --cache-image $ECR_REGISTRY/$ECR_REPO:cache \
          --publish
