name: "Teardown Review App"
on:
  pull_request:
    types: [closed]

env:
  ECR_REPO: fleet-ecr
  PROJECT: request-bin # request-bin
  SUBNET_NAME: fleet-apps # Fleet-Subnet
  SG_NAME: fleet-apps-cluster # Fleet-Security-3
  FS_TOKEN: fleet-apps # FleetFS
  REGION: us-east-2 # us-east-2
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  teardown:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Required Environment Variables
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "SUBNET_ID=$( \
            aws ec2 describe-subnets \
              --filters Name=tag:Name,Values=$SUBNET_NAME \
              --query 'Subnets[0].SubnetId' \
              --output text)" >> $GITHUB_ENV
          echo "SG_ID=$( \
            aws ec2 describe-security-groups \
              --filters Name=group-name,Values=$SG_NAME \
              --query 'SecurityGroups[0].GroupId' \
              --output text)" >> $GITHUB_ENV
          echo "TASK_EXECUTION_ROLE_ARN=$( \
            aws iam get-role \
              --role-name fleetTaskExecutionRole \
              --query 'Role.Arn' \
              --output text)" >> $GITHUB_ENV
          echo "FS_ID=$( \
            aws efs describe-file-systems \
              --creation-token $FS_TOKEN \
              --query 'FileSystems[0].FileSystemId' \
              --output text)" >> $GITHUB_ENV

      - name: Cleanup ECS
        id: cleanup-ecs
        uses: ./.github/actions/cleanup-ecs

      - name: Clear EFS
        id: clear-efs
        uses: ./.github/actions/clear-efs
