name: Test Environment Variables
on: [push]

env:
  SQL_FILE: server/db/migration.sql
  ECR_REGISTRY: reg
  ECR_REPO: chris
  PROJECT: stuff
  PR_NUMBER: 3
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: make arbitrary environment variables
        env:
          THIS: "repository"
          EXAMPLE: "name"
          SUCKS: "tag"
          NUMBER: "version"
        run: |
          echo "thing=`$THIS/$EXAMPLE:$SUCKS-$NUMBER`" >> $GITHUB_ENV
      - run: |
        echo ${{ env.thing }}
