name: Test Docker Heredoc
on: [push]

env:
  SQL_FILE: server/db/migration.sql
  ECR_REGISTRY: reg
  ECR_REPO: chris
  PROJECT: stuff
  PR_NUMBER: 3
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Create image for SQL Seeder
        id: make-sql-seeder
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:$PROJECT-$PR_NUMBER -f- .  <<EOF
          FROM alpine:3.13
          COPY $SQL_FILE init.sql
          RUN echo -e '#!/bin/bash\nmv init.sql efs-file-transfer\nls efs-file-transfer' > ./entrypoint.sh
          RUN ["chmod", "+x", "./entrypoint.sh"]
          ENTRYPOINT ["./entrypoint.sh"]
          EOF
      - run: docker images
